# settings

SETTINGS_STEPS = 12
SETTINGS_FPS = 8
SETTINGS_EASING = 'ease-linear'  # linear, in, out, in-and-out, centre, blend, blend-2
SETTINGS_CENTRE = False
SETTINGS_WIDTH = 2400  
SETTINGS_HEIGHT = 1800
SETTINGS_PREVIEW = True
SETTINGS_MODE = 'production'

# output settings

ALIGN_PATH_ORDER = True
CURVE_SMOOTHING = 1
IGNORE_SORTED = True

# matching

SCALE_X = 1.5
SCALE_Y = 1.5
SCALE_LENGTH = 1.7
SCALE_INTERNAL_ANGLE = 0.25
SCALE_SIBLING_MAGNITUDE = 0.5
SCALE_SIBLING_ANGLE = 2.5
SCALE_SIBLING_LENGTH = 0.1
SIBLING_COUNT = 10
SCALE_TOTAL_ANGLE = 0
SCALE_WIDTH = 0.05
SCALE_HEIGHT = 0.05
SCALE_NUMBER_POINTS = 0.25
SCALE_INDEX = 0

# colours

LINE_COLOUR = "black";
FILL_COLOUR = False
COLOUR_MODE = "exclude";
COLOUR_MAP = []
    
    